### PR TITLE
Fix IMOS check_coordinate_variables for monotonic values

### LINKED ISSUE #99: dimension monotocity not checked
Just realised that some of my soop trv files I get from AIMS have a time variable which is not monotonic.
See for example this file:
[IMOS_SOOP-TRV_B_20080930T002727Z_VNCF_FV01_END-20081002T000000Z_C-20160120T154802Z.nc.no.monotonic.zip](https://github.com/aodn/compliance-checker/files/96999/IMOS_SOOP-TRV_B_20080930T002727Z_VNCF_FV01_END-20081002T000000Z_C-20160120T154802Z.nc.no.monotonic.zip)

doing a `ncdump -t -v TIME`  will show the issue. for example, look for `2012` values. The issue is both CF and IMOS checker don't see that the TIME dimension is not monotonic, which surprises me a bit

### PR DESCRIPTION
**Pull request by mhidas**
This will fix #99 and also a minor bug I noticed on the way.

### CODE REVIEW

**Comment by mhidas** [comment]
The changes to imos_bad_data.cdl were:

```
3c3,4
<   time = 10 ;
---
>   ticks = 10 ;
>         bobs = 4 ;
5c6
<   float TIME(time) ;
---
>   float TIME(ticks) ;
29,34c30,37
<   double time(time) ;
<       time:standard_name = "" ;
<       time:valid_min = "" ;
<       time:valid_max = "" ;
<       time:calendar = "" ;
<       time:long_name = 123L ;
---
>   double ticks(ticks) ;
>       ticks:standard_name = "" ;
>       ticks:valid_min = "" ;
>       ticks:valid_max = "" ;
>       ticks:calendar = "" ;
>       ticks:long_name = 123L ;
>         float bobs(bobs) ;
> 
47d49
<       :_FillValue = 0L ;
79c81,83
<  time = _, _, _, _, _, _, _, _, _, _ ;
---
>  ticks = 21500.0, 21500.1, 21500.2, 21500.3, 21500.9, 21500.8, 21500.7, 21500.6, 21500.4, 21500.5 ;
> 
>  bobs = 1, 2, 2, 4 ;

```

**Comment by mhidas** [comment]
@lbesnard @ggalibert Please review

**Comment by lbesnard** [comment]
@mhidas  quick question, this shouldn't be a  cf test ?

**Comment by mhidas** [comment]
@lbesnard Yes, it probably should. E.g. the [definition](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#terminology) of a "coordinate variable" is

> We use this term precisely as it is defined in section 2.3.1 of the NUG . It is a one-dimensional variable with the same name as its dimension [e.g., time(time) ], and it is defined as a numeric data type with values that are ordered monotonically. Missing values are not allowed in coordinate variables. 

Feel free to report it at https://github.com/ioos/compliance-checker

**Comment by lbesnard** [comment]
works well with me

**Pull request merged**
